language: php

dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DBASE=no
  - DBASE=yes

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1
      name: "Coding standard"
      script: vendor/bin/phpcs
    - php: 7.1
      name: "Static analysis"
      env: DBASE=yes
      script: vendor/bin/phpstan analyze
    - php: nightly
      env: DBASE=no
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: nightly
      env: DBASE=yes
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: 7.2
      name: "API docs"
      before_install: phpenv config-rm xdebug.ini
      after_success: skip
      install:
        - composer global require "code-lts/doctum:^5.0"
        - composer install --no-interaction
      script:
        - $HOME/.composer/vendor/bin/doctum.php --no-interaction update ./ci/doctum-config.php || $HOME/.composer/vendor/bin/doctum.php --no-interaction parse ./ci/doctum-config.php

before_install:
  - |
    if [[ "$DBASE" == "yes" ]]; then
        pecl channel-update pecl.php.net
        pecl install dbase
    fi

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
  - cd examples
  - php create_shapefile.php
  - php read_point.php > /dev/null
  - php read_polygon.php > /dev/null
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
